name: Deploy to GCS

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: projectps  # Replace with your Google Cloud Project ID

      - name: Deploy to GCS
        run: |
          gsutil rsync -r . gs://shrey-snowviz-platform/app